language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra

script:
  - gradle build
  - gradle check

notifications:
  slack:
    rooms:
      - theotech:8ohw5Y0oeSjwtLsDp4bnyZwB

after_failure:
  - cat /home/travis/build/ceaseless-prayer/CeaselessAndroid/app/build/outputs/lint-results.xml 
