language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - build-tools-28.0.3
    - android-27
    - extra

# HACK for android-27 https://github.com/travis-ci/travis-ci/issues/8874
before_install:
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew build
  - ./gradlew check

notifications:
  slack:
    rooms:
      - theotech:8ohw5Y0oeSjwtLsDp4bnyZwB

after_failure:
  - cat /home/travis/build/ceaseless-prayer/CeaselessAndroid/app/build/outputs/lint-results.xml 

env:
  - GRADLE_OPTS="-Xmx2048m -Xms256m"

jdk:
  - oraclejdk8
