language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra

script:
  - gradle build
  - gradle check

notifications:
  slack:
    rooms:
      - theotech:8ohw5Y0oeSjwtLsDp4bnyZwB
